// Top 200 cities for SEO soin×ville pages
// Generated from RPPS data (cities with most IDEL) + top population cities
export const TOP_CITIES = [
  { name: "Paris", postal: "75001", slug: "paris", metro: true, metroKey: "paris" },
  { name: "Marseille", postal: "13001", slug: "marseille", metro: true, metroKey: "marseille" },
  { name: "Lyon", postal: "69001", slug: "lyon", metro: true, metroKey: "lyon" },
  { name: "Toulouse", postal: "31000", slug: "toulouse" },
  { name: "Bordeaux", postal: "33000", slug: "bordeaux" },
  { name: "Lille", postal: "59000", slug: "lille" },
  { name: "Rennes", postal: "35000", slug: "rennes" },
  { name: "Strasbourg", postal: "67000", slug: "strasbourg" },
  { name: "Nantes", postal: "44000", slug: "nantes" },
  { name: "Montpellier", postal: "34000", slug: "montpellier" },
  { name: "Grenoble", postal: "38000", slug: "grenoble" },
  { name: "Dijon", postal: "21000", slug: "dijon" },
  { name: "Angers", postal: "49000", slug: "angers" },
  { name: "Orleans", postal: "45000", slug: "orleans" },
  { name: "Rouen", postal: "76000", slug: "rouen" },
  { name: "Caen", postal: "14000", slug: "caen" },
  { name: "Nancy", postal: "54000", slug: "nancy" },
  { name: "Tours", postal: "37000", slug: "tours" },
  { name: "Limoges", postal: "87000", slug: "limoges" },
  { name: "Amiens", postal: "80000", slug: "amiens" },
  { name: "Clermont-Ferrand", postal: "63000", slug: "clermont-ferrand" },
  { name: "Nice", postal: "06000", slug: "nice" },
  { name: "Toulon", postal: "83000", slug: "toulon" },
  { name: "Saint-Denis", postal: "97490", slug: "saint-denis" },
  { name: "Saint-Étienne", postal: "42100", slug: "saint-etienne" },
  { name: "Perpignan", postal: "66000", slug: "perpignan" },
  { name: "Nîmes", postal: "30000", slug: "nimes" },
  { name: "Le Havre", postal: "76600", slug: "le-havre" },
  { name: "Aix-En-Provence", postal: "13090", slug: "aix-en-provence" },
  { name: "Béziers", postal: "34500", slug: "beziers" },
  { name: "Saint-Pierre", postal: "97410", slug: "saint-pierre" },
  { name: "Saint-Paul", postal: "97460", slug: "saint-paul" },
  { name: "Pau", postal: "64000", slug: "pau" },
  { name: "Dunkerque", postal: "59240", slug: "dunkerque" },
  { name: "Saint-André", postal: "97440", slug: "saint-andre" },
  { name: "Tourcoing", postal: "59200", slug: "tourcoing" },
  { name: "Reims", postal: "51100", slug: "reims" },
  { name: "Le Tampon", postal: "97430", slug: "le-tampon" },
  { name: "Bastia", postal: "20200", slug: "bastia" },
  { name: "Antibes", postal: "06600", slug: "antibes" },
  { name: "Ajaccio", postal: "20090", slug: "ajaccio" },
  { name: "Villeurbanne", postal: "69100", slug: "villeurbanne" },
  { name: "Cagnes-Sur-Mer", postal: "06800", slug: "cagnes-sur-mer" },
  { name: "Le Lamentin", postal: "97232", slug: "le-lamentin" },
  { name: "Cannes", postal: "06400", slug: "cannes" },
  { name: "Montauban", postal: "82000", slug: "montauban" },
  { name: "Port-De-Bouc", postal: "13110", slug: "port-de-bouc" },
  { name: "Brest", postal: "29200", slug: "brest" },
  { name: "Besançon", postal: "25000", slug: "besancon" },
  { name: "La Seyne-Sur-Mer", postal: "83500", slug: "la-seyne-sur-mer" },
  { name: "Biarritz", postal: "64200", slug: "biarritz" },
  { name: "Fréjus", postal: "83600", slug: "frejus" },
  { name: "Avignon", postal: "84000", slug: "avignon" },
  { name: "Fort-De-France", postal: "97200", slug: "fort-de-france" },
  { name: "Sète", postal: "34200", slug: "sete" },
  { name: "Le Mans", postal: "72000", slug: "le-mans" },
  { name: "Hyères", postal: "83400", slug: "hyeres" },
  { name: "Aubagne", postal: "13400", slug: "aubagne" },
  { name: "Saint-Joseph", postal: "97480", slug: "saint-joseph" },
  { name: "Les Abymes", postal: "97139", slug: "les-abymes" },
  { name: "Narbonne", postal: "11100", slug: "narbonne" },
  { name: "Arles", postal: "13200", slug: "arles" },
  { name: "Brive-La-Gaillarde", postal: "19100", slug: "brive-la-gaillarde" },
  { name: "Valence", postal: "26000", slug: "valence" },
  { name: "Le Cannet", postal: "06110", slug: "le-cannet" },
  { name: "Metz", postal: "57000", slug: "metz" },
  { name: "Saint-Louis", postal: "97421", slug: "saint-louis" },
  { name: "Saint-Raphaël", postal: "83700", slug: "saint-raphael" },
  { name: "Lorient", postal: "56100", slug: "lorient" },
  { name: "Mulhouse", postal: "68100", slug: "mulhouse" },
  { name: "Six-Fours-Les-Plages", postal: "83140", slug: "six-fours-les-plages" },
  { name: "Carcassonne", postal: "11000", slug: "carcassonne" },
  { name: "La Rochelle", postal: "17000", slug: "la-rochelle" },
  { name: "Cherbourg-En-Cotentin", postal: "50100", slug: "cherbourg-en-cotentin" },
  { name: "Sanary-Sur-Mer", postal: "83110", slug: "sanary-sur-mer" },
  { name: "Albi", postal: "81000", slug: "albi" },
  { name: "Sainte-Marie", postal: "97230", slug: "sainte-marie" },
  { name: "Vannes", postal: "56000", slug: "vannes" },
  { name: "La Ciotat", postal: "13600", slug: "la-ciotat" },
  { name: "Castres", postal: "81100", slug: "castres" },
  { name: "Saint-Quentin", postal: "02100", slug: "saint-quentin" },
  { name: "Martigues", postal: "13500", slug: "martigues" },
  { name: "Tarbes", postal: "65000", slug: "tarbes" },
  { name: "Saint-Malo", postal: "35400", slug: "saint-malo" },
  { name: "Romans-Sur-Isère", postal: "26100", slug: "romans-sur-isere" },
  { name: "Colmar", postal: "68000", slug: "colmar" },
  { name: "Cayenne", postal: "97300", slug: "cayenne" },
  { name: "Gap", postal: "05000", slug: "gap" },
  { name: "Pointe-À-Pitre", postal: "97110", slug: "pointe-a-pitre" },
  { name: "Calais", postal: "62100", slug: "calais" },
  { name: "Alès", postal: "30100", slug: "ales" },
  { name: "Miramas", postal: "13140", slug: "miramas" },
  { name: "Maubeuge", postal: "59600", slug: "maubeuge" },
  { name: "Roubaix", postal: "59100", slug: "roubaix" },
  { name: "Wattrelos", postal: "59150", slug: "wattrelos" },
  { name: "Créteil", postal: "94000", slug: "creteil" },
  { name: "Cambrai", postal: "59400", slug: "cambrai" },
  { name: "Anglet", postal: "64600", slug: "anglet" },
  { name: "Grasse", postal: "06130", slug: "grasse" },
  { name: "Quimper", postal: "29000", slug: "quimper" },
  { name: "Charleville-Mézières", postal: "08000", slug: "charleville-mezieres" },
  { name: "Arras", postal: "62000", slug: "arras" },
  { name: "Mérignac", postal: "33700", slug: "merignac" },
  { name: "Saint-Nazaire", postal: "44600", slug: "saint-nazaire" },
  { name: "Villenave-D'Ornon", postal: "33140", slug: "villenave-d-ornon" },
  { name: "Schoelcher", postal: "97233", slug: "schoelcher" },
  { name: "Salon-De-Provence", postal: "13300", slug: "salon-de-provence" },
  { name: "Saint-Priest", postal: "69800", slug: "saint-priest" },
  { name: "Annecy", postal: "74000", slug: "annecy" },
  { name: "Draguignan", postal: "83300", slug: "draguignan" },
  { name: "Sevran", postal: "93270", slug: "sevran" },
  { name: "Argenteuil", postal: "95100", slug: "argenteuil" },
  { name: "Sainte-Rose", postal: "97115", slug: "sainte-rose" },
  { name: "Pessac", postal: "33600", slug: "pessac" },
  { name: "Saint-Chamond", postal: "42400", slug: "saint-chamond" },
  { name: "Saint-Cyr-Sur-Mer", postal: "83270", slug: "saint-cyr-sur-mer" },
  { name: "Bayonne", postal: "64100", slug: "bayonne" },
  { name: "La Valette-Du-Var", postal: "83160", slug: "la-valette-du-var" },
  { name: "Basse-Terre", postal: "97100", slug: "basse-terre" },
  { name: "Istres", postal: "13800", slug: "istres" },
  { name: "Montélimar", postal: "26200", slug: "montelimar" },
  { name: "Cavaillon", postal: "84300", slug: "cavaillon" },
  { name: "Poitiers", postal: "86000", slug: "poitiers" },
  { name: "Le Moule", postal: "97160", slug: "le-moule" },
  { name: "Marignane", postal: "13700", slug: "marignane" },
  { name: "Vénissieux", postal: "69200", slug: "venissieux" },
  { name: "Boulogne-Billancourt", postal: "92100", slug: "boulogne-billancourt" },
  { name: "La Fare-Les-Oliviers", postal: "13580", slug: "la-fare-les-oliviers" },
  { name: "Ollioules", postal: "83190", slug: "ollioules" },
  { name: "Vitry-Sur-Seine", postal: "94400", slug: "vitry-sur-seine" },
  { name: "Arcachon", postal: "33120", slug: "arcachon" },
  { name: "Vaulx-En-Velin", postal: "69120", slug: "vaulx-en-velin" },
  { name: "Chambéry", postal: "73000", slug: "chambery" },
  { name: "Bourges", postal: "18000", slug: "bourges" },
  { name: "Agde", postal: "34300", slug: "agde" },
  { name: "Roanne", postal: "42300", slug: "roanne" },
  { name: "Villeneuve-D'Ascq", postal: "59650", slug: "villeneuve-d-ascq" },
  { name: "Saint-Benoît", postal: "97470", slug: "saint-benoit" },
  { name: "Évry-Courcouronnes", postal: "91000", slug: "evry-courcouronnes" },
  { name: "Mont-De-Marsan", postal: "40000", slug: "mont-de-marsan" },
  { name: "Vallauris", postal: "06220", slug: "vallauris" },
  { name: "Colombes", postal: "92700", slug: "colombes" },
  { name: "Saint-Leu", postal: "97424", slug: "saint-leu" },
  { name: "Vence", postal: "06140", slug: "vence" },
  { name: "La Teste-De-Buch", postal: "33260", slug: "la-teste-de-buch" },
  { name: "Saint-Médard-En-Jalles", postal: "33160", slug: "saint-medard-en-jalles" },
  { name: "Châteauroux", postal: "36000", slug: "chateauroux" },
  { name: "Douai", postal: "59500", slug: "douai" },
  { name: "Sarcelles", postal: "95200", slug: "sarcelles" },
  { name: "Le Gosier", postal: "97190", slug: "le-gosier" },
  { name: "Pamiers", postal: "09100", slug: "pamiers" },
  { name: "Aix-Les-Bains", postal: "73100", slug: "aix-les-bains" },
  { name: "Carpentras", postal: "84200", slug: "carpentras" },
  { name: "Bourg-En-Bresse", postal: "01000", slug: "bourg-en-bresse" },
  { name: "Menton", postal: "06500", slug: "menton" },
  { name: "Floirac", postal: "33270", slug: "floirac" },
  { name: "Haguenau", postal: "67500", slug: "haguenau" },
  { name: "Niort", postal: "79000", slug: "niort" },
  { name: "Les Sables-D'Olonne", postal: "85100", slug: "les-sables-d-olonne" },
  { name: "Marcq-En-Baroeul", postal: "59700", slug: "marcq-en-baroeul" },
  { name: "Sainte-Anne", postal: "97180", slug: "sainte-anne" },
  { name: "Boulogne-Sur-Mer", postal: "62200", slug: "boulogne-sur-mer" },
  { name: "Libourne", postal: "33500", slug: "libourne" },
  { name: "Voiron", postal: "38500", slug: "voiron" },
  { name: "Villefranche-Sur-Saône", postal: "69400", slug: "villefranche-sur-saone" },
  { name: "Saint-Maur-Des-Fossés", postal: "94100", slug: "saint-maur-des-fosses" },
  { name: "Montluçon", postal: "03100", slug: "montlucon" },
  { name: "Rodez", postal: "12000", slug: "rodez" },
  { name: "Bègles", postal: "33130", slug: "begles" },
  { name: "La Roche-Sur-Yon", postal: "85000", slug: "la-roche-sur-yon" },
  { name: "Douarnenez", postal: "29100", slug: "douarnenez" },
  { name: "Chalon-Sur-Saône", postal: "71100", slug: "chalon-sur-saone" },
  { name: "Périgueux", postal: "24000", slug: "perigueux" },
  { name: "Muret", postal: "31600", slug: "muret" },
  { name: "Orange", postal: "84100", slug: "orange" },
  { name: "Saint-Martin", postal: "97150", slug: "saint-martin" },
  { name: "Digne-Les-Bains", postal: "04000", slug: "digne-les-bains" },
  { name: "Valenciennes", postal: "59300", slug: "valenciennes" },
  { name: "Le Pontet", postal: "84130", slug: "le-pontet" },
  { name: "Allauch", postal: "13190", slug: "allauch" },
  { name: "Vitrolles", postal: "13127", slug: "vitrolles" },
  { name: "Ploemeur", postal: "56270", slug: "ploemeur" },
  { name: "Caluire-Et-Cuire", postal: "69300", slug: "caluire-et-cuire" },
  { name: "Mandelieu-La-Napoule", postal: "06210", slug: "mandelieu-la-napoule" },
  { name: "Petit-Bourg", postal: "97170", slug: "petit-bourg" },
  { name: "Manosque", postal: "04100", slug: "manosque" },
  { name: "Bergerac", postal: "24100", slug: "bergerac" },
  { name: "Vienne", postal: "38200", slug: "vienne" },
  { name: "Lens", postal: "62300", slug: "lens" },
  { name: "Millau", postal: "12100", slug: "millau" },
  { name: "Gradignan", postal: "33170", slug: "gradignan" },
  { name: "Frontignan", postal: "34110", slug: "frontignan" },
  { name: "Villeneuve-Sur-Lot", postal: "47300", slug: "villeneuve-sur-lot" },
  { name: "Châlons-En-Champagne", postal: "51000", slug: "chalons-en-champagne" },
  { name: "Hem", postal: "59510", slug: "hem" },
  { name: "Clamart", postal: "92140", slug: "clamart" },
  { name: "Saint-Brieuc", postal: "22000", slug: "saint-brieuc" },
  { name: "Auch", postal: "32000", slug: "auch" },
  { name: "Eysines", postal: "33320", slug: "eysines" },
  { name: "Agen", postal: "47000", slug: "agen" },
]
